### ISSUE TITLE
make README config setting more explicit

### ISSUE THREAD

**Issue by sanchamp** [d3plus/d3plus-react#13]

**Comment by davelandry** [comment]
I have made the README docs more explicit: https://github.com/d3plus/d3plus-react/blob/master/README.md

You pass an `Object` to the config prop, and that object contains keys that match the methods you would be setting.

**Comment by sanchamp** [comment]
Thanks, Dave! It's really amazing library and I love programming with it.



‌

**Comment by sanchamp** [comment]
Can I use d3-shotchart with d3plus-react?



<https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=sandeeppatil.patil@gmail.com&idSignature=22>

**Comment by davelandry** [comment]
@sanchamp d3plus-react only works with the d3plus charting libraries, which are all found here: https://github.com/d3plus

**Comment by sanchamp** [comment]
Thanks, Dave! Can you help me with how I can use data from the external
file. I tried but I can't see the output and no error is displayed.

import React, { Component } from "react";
import { LinePlot } from "d3plus-react";
import { csv } from "d3-request";

class Timedown extends Component {
  state = {};

  componentDidMount() {
    csv("./data/d3plus.csv", (error, data) => {
      if (error) {
        this.setState({ loadError: true });
      }
      console.log(data);
      this.setState({
        data: data.map(d => ({ ...d, x: Number(d.year), y: Number(d.value) }))
      });
    });
  }

  render() {
    if (this.state.loadError) {
      return <div>couldn't load file</div>;
    }
    if (!this.state.data) {
      return <div />;
    }
    const { data } = this.state;
    // console.log(data);
    // const config = {
    //   data,
    //   x: "year",
    //   y: "value",
    //   text: "name"
    // };
    return data ? <LinePlot config={{ data }} /> : <p>No Data!</p>;
  }
}

export default Timedown;

**Comment by davelandry** [comment]
@sanchamp d3plus can handle loading the file for you, and you can supply a custom `dataFormat` prop that formats the loaded data:

```jsx
import React, { Component } from "react";
import { LinePlot } from "d3plus-react";

class Timedown extends Component {

  formatter(data) {
    return data.map(d => ({ ...d, x: Number(d.year), y: Number(d.value) }));
  }

  render() {

    const config = {
      data: "./data/d3plus.csv",
      x: "year",
      y: "value",
      text: "name"
    };

    return <LinePlot config={config} dataFormat={this.formatter} />;
  }
}

export default Timedown;
```

**Comment by sanchamp** [comment]
![image](https://user-images.githubusercontent.com/19597513/31564028-6dc32b94-b02f-11e7-9799-8a1731cd9773.png)

![image](https://user-images.githubusercontent.com/19597513/31564049-7c3aaf80-b02f-11e7-8b03-05bee4cc7483.png)
![image](https://user-images.githubusercontent.com/19597513/31564108-ab920468-b02f-11e7-87d2-bc2b8633077d.png)

Thanks for your reply Dave, code still not working!

**Comment by sanchamp** [comment]
Hello Dave, I'm getting issue as "You need to enable JavaScript to run this app." even if the javascript is enabled for browser

**Comment by sanchamp** [comment]
Thank you Dave, I got the solution. No need to reply.
