### ISSUE TITLE
visualizations no longer setting default className to viz

### ISSUE THREAD

**Issue by jspeis** [d3plus/d3plus-react#21]
Was trying to chase an issue down with some weird styling that broke after an upgrade. Looks like the CSS in the project was relying on having d3plus visualizations like `<Geomap>` get wrapped by default in a class with the name `viz`. But seems like that is no longer the default behavior. 

Possible cause might be even though [Viz.js](https://github.com/d3plus/d3plus-react/blob/master/src/Viz.js) sets `defaultProps` with  `className: "viz"` it looks like other instances e.g. [Geomap](https://github.com/d3plus/d3plus-react/blob/master/src/Geomap.js) wipe that out by overwriting the default props on the class: `Geomap.defaultProps = {type};`

**Comment by davelandry** [comment]
Fixed with #22
