### ISSUE TITLE
Active function in Network component 

### ISSUE THREAD

**Issue by AlmahaAlmalki** [d3plus/d3plus-react#32]
Hi, 

I’m trying to add a search function to search the network nodes based on ids. Is there a way to activate a particular node to have a similar effect to "node click"? 

<img width="807" alt="Screenshot 2019-12-29 01 00 01" src="https://user-images.githubusercontent.com/11076091/71549914-96534080-29d6-11ea-8e45-38d17d549fdc.png">

I tried to trigger a click event on the selected node, but it didn't work. 

```
active: d => {
     if(d['id'] === node) {
          let id = `d3plus-Shape d3plus-Circle d3plus-id-${d['id']}`
          let n = document.getElementsByClassName(id)
          n.click()
    }
```

I also tried this approach

```
let node = "914"
Network.config({
     active: d => {
         if(d['id'] === node) {
              return true
         }     
      return false               
     }
  }).render() 
```

**Comment by davelandry** [comment]
@AlmahaAlmalki mouse events can be added/overridden using the `on` config, with nested even handlers within it: http://d3plus.org/examples/d3plus-hierarchy/mouse-events/

Adding a snippit here as well:

```js
.config({
  on: {
    click: d => console.log(`Hello, I am ${d.id}`)
  }
})
```
