### ISSUE TITLE
.d3plus.js documentation in README out of date

### ISSUE THREAD

**Issue by jspeis** [d3plus/d3plus-react#39]
The current README mentions the possibility of using a global .d3plus.js config file, but it seems [this functionality was removed in favor of context based loading](https://github.com/d3plus/d3plus-react/commit/cf6ea8fc6749752bbae16a3aa6333d3b41465eaf)

### Expected Behavior

Could be nice to have updated examples in the README of context providers

**Comment by davelandry** [comment]
just updated this @jspeis, be a second set of eyes and see if what I wrote makes sense? 😅
