### ISSUE TITLE
Percentage on custom treemap label

### ISSUE THREAD

**Issue by fabripetrelli** [d3plus/d3plus-react#46]
Hi, 

I'm trying to have a custom treemap tile with the name and the percentage like the stock one but I need to manually modify it because on the data that I have the IDs of the tiles aren't unique.

Here's my mocked dataset:

```
  const newData = [
    { parent: 'Group 1', id: 'alpha', value: 29 },
    { parent: 'Group 1', id: 'beta', value: 10 },
    { parent: 'Group 1', id: 'gamma', value: 2 },
    { parent: 'Group 2', id: 'alpha', value: 29 },
    { parent: 'Group 2', id: 'beta', value: 25 },
  ];
```

And here's my treemap config:

```
  const methods = {
    data: newData,
    groupBy: ['parent', 'id'],
    size: 'value',
    tooltipConfig: {
      title: (d) => `${d.parent} - <span>${d.name}</span>`,
    },
    shapeConfig: {
      label: (d) => {
        console.log(d);
        return [d.id, **_calculatedShareHere_**];
      },
    },
  };

```

How can I get the calculated share?

**Comment by davelandry** [comment]
@fabriziopaolopetrelli accessor functions are provided three arguments: your data point `d`, it's index `i`, and an internal d3plus object containing calculated positioning and math `x`.

Check out this example, you can grab the share percentage with `x.share * 100`: https://jsfiddle.net/q0aL1rd5/
