### ISSUE TITLE
bar charts axis starting at non-zero

### ISSUE THREAD

**Issue by sidhusubhash** [d3plus/d3plus-react#47]
Hi,

While changing the y-axis domain of a bar chart, bars are overlapping the x-axis. How can i avoid this?
<img width="609" alt="Screenshot 2021-09-10 at 6 24 33 PM" src="https://user-images.githubusercontent.com/36511816/132856360-5162be09-44c0-4190-9fa1-39ef224eceb6.png">

Version: "d3plus-react": "1.0.1'
Reference: https://github.com/d3plus/d3plus/issues/480

**Comment by sidhusubhash** [comment]
Reference: https://github.com/d3plus/d3plus/issues/480

**Comment by davelandry** [comment]
Instead of starting from zero (which is often a big "no no" in Bar Charts), I'd prefer to add support for "breaking" the scale: https://github.com/d3plus/d3plus/issues/767
