### ISSUE TITLE
v.1.2.0 does not have required packages

### ISSUE THREAD

**Issue by michelacerro** [d3plus/d3plus-react#53]
I installed the version 1.2.0 and that does not have the required packages. The `src` folder contains only D3PlusContext module, but not all the others (AreaPlot, BarChart and so on)

### Expected Behavior

Install the library, import the modules as the documentation explains to make it work

### Current Behavior

Install the library, import modul and get the error `ERROR in ./node_modules/d3plus-react/es/index.js 1:0-53
Module not found: Error: Can't resolve './src/AreaPlot' in` (the same for the other modules)

### Steps to Reproduce (for bugs)

1. Install the library with `npm install d3plus-react`
2. Create an example component and import a d3plus-react module

### Your Environment

* Browser Name: Chrome
* Operating System and Version: Ubuntu 20.04.5 LTS and macOS 12.6

**Comment by davelandry** [comment]
good catch @michelacerro, my apologies. Those files changed from `.js` to `.jsx` with the v1.2 release, and we did not update our glob pattern in the release script.

It should be fixed, can you try again with the v1.2.1 release and let us know if it works?

**Comment by michelacerro** [comment]
Hi @davelandry,
thank you very much for the fast reply and the bug fix. I tested the v.1.2.1 release and everything works fine.
Thanks again
