### ISSUE TITLE
Custom hover behavior

### ISSUE THREAD

**Issue by michelacerro** [d3plus/d3plus-react#55]
Hi everyone! 

I'm creating a Treemap and I need to customize it. Following the documentation and making a few attempts, I was able to make all the changes that interested me, with the exception of handling the hover behavior. 
I would need to create two separate custom behaviors for hovering over the chart and over the legend. Is this possible?

Up until now, I've tried modifying the `hover` and `mouseenter` methods, but to no avail.

Thanks a lot for your work.

Michela

**Comment by davelandry** [comment]
Hi @michelacerro, check out this other issue, which includes example code showing how to assign different functions to the shapes in the chart and the legend: https://github.com/d3plus/d3plus/issues/760

**Comment by michelacerro** [comment]
Hi @davelandry, thanks for the reply.

I've tried changing the "mouseenter.shape" and "mouseenter.legend" functions, but I can't figure out what they expect to return.
For clarity, in this specific case, I would like not only the element the mouse is over to go into the "hover" state, but also its siblings, the other elements belonging to its group.
What has to come back for their status to change too?
Or, if that's not possible, how can I access the nodes of these elements to be able to manually edit their style?
Could you give me an example?

Thanks in advance,

Michela

**Comment by davelandry** [comment]
@michelacerro the mouse event functions are not expected to return anything, but rather simply execute code when that even occurs.

What you are trying to do is possible, but might require some complex JavaScript to access some internal states of D3plus. If you use a name/non-anonymous function, like in the following example, you can get access to `this`, which is the internal state of the current viz executing the mouse event:

```js
on: {
  "mouseenter.shape": function myFunctionName(d) {
    const vizState = this;
    // do stuff here!
  }
}
```

Take a look at the default `mouseenter` function (which you may want to remove, by passing `null`). In it, it uses some internal (undocumented 😅) d3plus methods to identify the elements unique keys, and uses those to set the `hover` method. The `hover` method (publicly accessible) is what allows you to "highlight" certain data points, and is used internally for the default hover events. The function provided to `hover` is expected to return true or false based on the data point `d` passed to it (it is used internally as part of a `filter` function).

https://github.com/d3plus/d3plus-viz/blob/master/src/on/mouseenter.js

**Comment by michelacerro** [comment]
@davelandry thanks a lot for this explanation, it is very helpful! :blush:
